import { allowedBranch, authenticateApi, corsHeaders, errorMessage, finishRequest, json, readJson, requireScope, sha256 } from "./_integration-shared.mjs";
function page(url){const p=Math.max(1,Number(url.searchParams.get("page")||1));const limit=Math.max(1,Math.min(200,Number(url.searchParams.get("limit")||50)));return {p,limit,from:(p-1)*limit,to:p*limit-1};}
function branchFilter(query,auth,url){const requested=url.searchParams.get("branch_id");if(requested){if(!allowedBranch(auth,requested))throw Object.assign(new Error("Branch is not allowed for this API client"),{status:403});return {query:query.eq("branch_id",requested),branchId:requested};}if((auth.branch_ids||[]).length)return {query:query.in("branch_id",auth.branch_ids),branchId:null};return {query,branchId:null};}
function searchLike(query,url,columns){const s=url.searchParams.get("search")?.trim();if(!s)return query;return query.or(columns.map(c=>`${c}.ilike.%${s.replaceAll(",","")}%`).join(","));}
async function externalRef(admin,auth,type,externalId){return admin.from("integration_external_references").select("*").eq("client_id",auth.client_id).eq("entity_type",type).eq("external_id",externalId).maybeSingle();}
export default async(request)=>{
 const started=Date.now();const origin=request.headers.get("origin")||"*";if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(origin)});
 let ctx;
 try{
  ctx=await authenticateApi(request);const {admin,auth}=ctx;const url=new URL(request.url);let path=url.pathname.replace(/^\/api\/v1/,"").replace(/^\/\.netlify\/functions\/integration-api/,"")||"/";const pg=page(url);let data,count,branchId=null;
  if(request.method==="GET"&&path==="/meta"){requireScope(auth,"meta.read");data={api:"Tiny POS Integration API",version:"1.0.0",client:{id:auth.client_id,name:auth.client_name,scopes:auth.scopes,branch_ids:auth.branch_ids,rate_limit_per_minute:auth.rate_limit_per_minute},time:new Date().toISOString()};count=1;}
  else if(request.method==="GET"&&path==="/branches"){requireScope(auth,"branches.read");let q=admin.from("branches").select("id,code,name,is_active,created_at,updated_at",{count:"exact"}).eq("organization_id",auth.organization_id).eq("is_active",true);if((auth.branch_ids||[]).length)q=q.in("id",auth.branch_ids);const r=await q.order("name").range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else if(request.method==="GET"&&path==="/products"){requireScope(auth,"catalog.read");let q=admin.from("products").select("id,category_id,name,name_km,sku,barcode,description,unit_name,selling_price,currency,tax_percent,track_stock,allow_negative_stock,low_stock_threshold,is_active,created_at,updated_at,categories(id,name),product_images(id,secure_url,is_primary,sort_order),product_units(id,name,short_name,conversion_factor,selling_price,barcode,is_base,is_active,sort_order)",{count:"exact"}).eq("organization_id",auth.organization_id);q=searchLike(q,url,["name","name_km","sku","barcode"]);const since=url.searchParams.get("updated_since");if(since)q=q.gte("updated_at",since);const r=await q.order("updated_at",{ascending:false}).range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else if(request.method==="GET"&&path==="/inventory"){requireScope(auth,"inventory.read");const includeCost=(auth.scopes||[]).includes("inventory.cost.read");let q=admin.from("inventory_balances").select(`id,branch_id,product_id,quantity,${includeCost?"average_cost,":""}updated_at,branches(id,code,name),products(id,name,name_km,sku,barcode,unit_name,currency,is_active)`,{count:"exact"}).eq("organization_id",auth.organization_id);({query:q,branchId}=branchFilter(q,auth,url));const r=await q.order("updated_at",{ascending:false}).range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else if(request.method==="GET"&&path==="/customers"){requireScope(auth,"customers.read");let q=admin.from("customers").select("id,customer_code,customer_type,name,company_name,phone,email,address,date_of_birth,loyalty_points,credit_limit,preferred_language,marketing_opt_in,crm_status,is_active,created_at,updated_at",{count:"exact"}).eq("organization_id",auth.organization_id);q=searchLike(q,url,["customer_code","name","company_name","phone","email"]);const since=url.searchParams.get("updated_since");if(since)q=q.gte("updated_at",since);const r=await q.order("updated_at",{ascending:false}).range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else if(request.method==="POST"&&path==="/customers"){requireScope(auth,"customers.write");const body=await readJson(request);const externalId=String(body.external_id||"").trim();const customer=body.customer||{};if(!externalId)throw new Error("external_id is required");if(!String(customer.name||"").trim())throw new Error("customer.name is required");const hash=sha256(JSON.stringify(customer));const ref=await externalRef(admin,auth,"customer",externalId);if(ref.error)throw ref.error;const values={organization_id:auth.organization_id,name:String(customer.name).trim(),customer_type:["regular","vip","wholesale"].includes(customer.customer_type)?customer.customer_type:"regular",company_name:customer.company_name||null,phone:customer.phone||null,email:customer.email||null,address:customer.address||null,notes:customer.notes||null,credit_limit:Math.max(0,Number(customer.credit_limit||0)),preferred_language:customer.preferred_language==="km"?"km":"en",marketing_opt_in:Boolean(customer.marketing_opt_in),is_active:customer.is_active!==false};let result;if(ref.data){result=await admin.from("customers").update(values).eq("id",ref.data.internal_id).eq("organization_id",auth.organization_id).select("*").single();}else{result=await admin.from("customers").insert(values).select("*").single();}if(result.error)throw result.error;await admin.from("integration_external_references").upsert({organization_id:auth.organization_id,client_id:auth.client_id,entity_type:"customer",external_id:externalId,internal_id:result.data.id,payload_hash:hash,last_synced_at:new Date().toISOString()},{onConflict:"client_id,entity_type,external_id"});data={customer:result.data,external_id:externalId};count=1;}
  else if(request.method==="GET"&&path==="/invoices"){requireScope(auth,"sales.read");let q=admin.from("sales").select("id,branch_id,invoice_number,customer_id,cashier_id,status,payment_status,currency,subtotal,discount_amount,tax_amount,total_amount,paid_amount,change_amount,cost_amount,gross_profit,completed_at,created_at,updated_at,customers(id,customer_code,name,phone),branches(id,code,name)",{count:"exact"}).eq("organization_id",auth.organization_id);({query:q,branchId}=branchFilter(q,auth,url));const status=url.searchParams.get("status");if(status)q=q.eq("status",status);const r=await q.order("created_at",{ascending:false}).range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else if(request.method==="GET"&&path==="/purchase-orders"){requireScope(auth,"purchases.read");let q=admin.from("purchases").select("id,branch_id,purchase_number,supplier_id,status,currency,subtotal,tax_amount,total_amount,amount_paid,supplier_invoice_number,notes,ordered_at,received_at,created_at,updated_at,suppliers(id,name,phone),branches(id,code,name)",{count:"exact"}).eq("organization_id",auth.organization_id);({query:q,branchId}=branchFilter(q,auth,url));const status=url.searchParams.get("status");if(status)q=q.eq("status",status);const r=await q.order("created_at",{ascending:false}).range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else if(request.method==="GET"&&path==="/online-orders"){requireScope(auth,"online_orders.read");let q=admin.from("online_orders").select("id,branch_id,order_number,status,payment_status,payment_method,fulfilment_type,currency,customer_id,customer_name,customer_phone,customer_email,delivery_address,requested_date,subtotal,delivery_fee,total_amount,sales_order_id,created_at,updated_at,branches(id,code,name)",{count:"exact"}).eq("organization_id",auth.organization_id);({query:q,branchId}=branchFilter(q,auth,url));const status=url.searchParams.get("status");if(status)q=q.eq("status",status);const r=await q.order("created_at",{ascending:false}).range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else if(request.method==="POST"&&path==="/online-orders"){requireScope(auth,"online_orders.write");const body=await readJson(request);const externalId=String(body.external_id||request.headers.get("idempotency-key")||"").trim();if(!externalId)throw new Error("external_id or Idempotency-Key is required");const ref=await externalRef(admin,auth,"online_order",externalId);if(ref.error)throw ref.error;if(ref.data){const existing=await admin.from("online_orders").select("*").eq("id",ref.data.internal_id).single();if(existing.error)throw existing.error;data={duplicate:true,order:existing.data,external_id:externalId};count=1;}else{const slug=String(body.store_slug||"").trim();if(!slug)throw new Error("store_slug is required so Tiny POS can recalculate prices safely");if(body.branch_id&&!allowedBranch(auth,body.branch_id))throw Object.assign(new Error("Branch is not allowed"),{status:403});const r=await admin.rpc("submit_online_order",{p_slug:slug,p_payload:body.order||body.payload||{},p_source_ip_hash:null,p_user_agent:"Tiny POS Integration API"});if(r.error)throw r.error;await admin.from("integration_external_references").insert({organization_id:auth.organization_id,client_id:auth.client_id,entity_type:"online_order",external_id:externalId,internal_id:r.data.order_id,payload_hash:sha256(JSON.stringify(body)),last_synced_at:new Date().toISOString()});data={duplicate:false,...r.data,external_id:externalId};count=1;}}
  else if(request.method==="GET"&&path==="/accounting/journals"){requireScope(auth,"accounting.read");let q=admin.from("accounting_journal_entries").select("id,branch_id,journal_number,journal_date,journal_type,status,currency,reference_type,reference_id,description,posted_at,created_at,updated_at",{count:"exact"}).eq("organization_id",auth.organization_id);({query:q,branchId}=branchFilter(q,auth,url));const r=await q.order("journal_date",{ascending:false}).range(pg.from,pg.to);if(r.error)throw r.error;data=r.data;count=r.count;}
  else throw Object.assign(new Error("API endpoint not found"),{status:404});
  await finishRequest(admin,auth,200,Date.now()-started,Array.isArray(data)?data.length:count,branchId);return json({ok:true,data,pagination:{page:pg.p,limit:pg.limit,total:count??(Array.isArray(data)?data.length:1)}},200,corsHeaders(ctx.origin||"*"));
 }catch(error){const status=error.status||500;if(ctx?.admin&&ctx?.auth)await finishRequest(ctx.admin,ctx.auth,status,Date.now()-started,null,null,errorMessage(error));return json({ok:false,error:errorMessage(error),details:error.details||undefined},status,{...corsHeaders(origin),...(status===429?{"Retry-After":String(error.details?.retry_after_seconds||60)}:{})});}
};
